---

- name: Assert the target host runs Red Hat
  assert:
    that: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

  - name: Install repositories
    yum: name=centos-release-scl state=present

  - name: Enable scl repos
    command: yum-config-manager --enable centos-sclo-rh-testing

  - name: Update yum's cache
    command: yum -y makecache
    tags:
      - skip_ansible_lint

  when:
    - ansible_distribution == 'CentOS'
  become: true

- name: Install Python 3.6 SCL
  yum:
    name: rh-python36
    state: present
  become: true

# EPEL provides Redis
- name: Enable EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  become: true
  register: result

- name: Update yum's cache
  command: yum -y makecache
  when: result is changed
  become: true
  tags:
    - skip_ansible_lint
